name: SATURN LK

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 43800

    steps:
    - name: Disable Firewall Profiles
      run: |
        try {
          Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
        } catch {
          Write-Host "Failed to disable firewall. Continuing..."
        }

    - name: Check if Google Chrome is Installed
      run: |
        $chromeInstalled = choco list --local-only | Select-String 'googlechrome'
        if ($chromeInstalled) {
          Write-Host "Google Chrome is already installed. Skipping installation."
        } else {
          Write-Host "Google Chrome not found. Installing..."

          # Direct link to Chrome standalone installer
          $chromeInstallerUrl = "https://dl.google.com/chrome/install/131.0.6778.140/chrome_installer.exe"
          $installerPath = "C:\Users\$Env:USERNAME\Downloads\chrome_installer.exe"
          
          # Download Chrome installer
          Invoke-WebRequest -Uri $chromeInstallerUrl -OutFile $installerPath
          
          # Install Chrome silently
          Start-Process -FilePath $installerPath -ArgumentList "/silent /install" -Wait
          Write-Host "Google Chrome installed successfully."
        }

    - name: Install Necessary Packages
      run: |
        function Install-PackageWithRetry {
            param ([string]$packageName)
            $maxRetries = 3
            $retryCount = 0
            while ($retryCount -lt $maxRetries) {
                try {
                    if (choco list --local-only | Select-String $packageName) {
                        Write-Host "$packageName is already installed. Skipping..."
                        return
                    }
                    choco install $packageName -y --ignore-checksums
                    Write-Host "$packageName installed successfully."
                    return
                } catch {
                    Write-Host "Retrying $packageName install ($($retryCount+1)/$maxRetries)"
                    Start-Sleep -Seconds 10
                    $retryCount++
                }
            }
            Write-Host "$packageName failed to install after multiple retries. Continuing..."
        }
        Install-PackageWithRetry -packageName "chrome-remote-desktop-host"

    - name: Download and Extract Free Fire Ripper
      continue-on-error: true
      run: |
        cd C:\Users\$Env:USERNAME\Documents
        try {
          Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=11EUFz6hufNT1g56-CmOJw9_KxMERZxhe&export=download" -OutFile ffripper.zip
          7z x ffripper.zip -y
        } catch {
          Write-Host "Download or extraction failed."
          exit 1
        }

    - name: Start Chrome Remote Desktop
      continue-on-error: true
      run: |
        function Start-RemoteDesktop {
          $paths = [
            "C:\Program Files\Chrome Remote Desktop\chrome_remote_desktop_host.exe",
            "C:\Program Files (x86)\Chrome Remote Desktop\chrome_remote_desktop_host.exe"
          ]
          foreach ($path in $paths) {
            if (Test-Path $path) {
              Start-Process $path
              Write-Host "Chrome Remote Desktop started."
              return
            }
          }
          Write-Host "Chrome Remote Desktop not found. Skipping..."
        }
        Start-RemoteDesktop
