name: FREE FIRE RIPPER

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Disable Firewall Profiles
      run: |
        try {
          Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
        } catch {
          Write-Host "Failed to disable firewall. Continuing..."
        }

    - name: Install Necessary Packages
      continue-on-error: true
      run: |
        function Install-PackageWithRetry {
            param ([string]$packageName)
            $maxRetries = 3
            $retryCount = 0
            while ($retryCount -lt $maxRetries) {
                try {
                    choco install $packageName -y
                    return
                } catch {
                    Write-Host "Retrying $packageName install ($($retryCount+1)/$maxRetries)"
                    Start-Sleep -Seconds 10
                    $retryCount++
                }
            }
            Write-Host "$packageName failed to install via Chocolatey."
        }
        Install-PackageWithRetry -packageName "chrome-remote-desktop-host"
        Install-PackageWithRetry -packageName "googlechrome"

    - name: Verify Installation of Chrome Remote Desktop
      continue-on-error: true
      run: |
        try {
          choco list --local-only | Select-String "chrome-remote-desktop-host"
          Write-Host "chrome-remote-desktop-host installed successfully."
        } catch {
          Write-Host "chrome-remote-desktop-host not found in Chocolatey list."
        }

        $command = Get-Command -Name "remoting_start_host.exe" -ErrorAction SilentlyContinue
        if ($null -eq $command) {
          Write-Host "remoting_start_host.exe was not found in the system."
        } else {
          Write-Host "remoting_start_host.exe is available."
        }

    - name: Download and Extract Free Fire Ripper
      continue-on-error: true
      run: |
        cd C:\Users\$Env:USERNAME\Documents
        try {
          Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=11EUFz6hufNT1g56-CmOJw9_KxMERZxhe&export=download" -OutFile ffripper.zip
          7z x ffripper.zip -y
        } catch {
          Write-Host "Download or extraction failed."
          exit 1
        }

    - name: Start Chrome Remote Desktop
      continue-on-error: true
      run: |
        function Start-RemoteDesktop {
          $path = Get-ChildItem -Path "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop" -Recurse -Filter "remoting_start_host.exe" -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
          if (-not $path) {
            $path = Get-ChildItem -Path "${Env:PROGRAMFILES}\Google\Chrome Remote Desktop" -Recurse -Filter "remoting_start_host.exe" -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
          }
          if ($path) {
            Write-Host "Found Chrome Remote Desktop at $path"
            & $path --code="${{ inputs.code }}" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin=123456
          } else {
            Write-Host "Chrome Remote Desktop's remoting_start_host.exe not found."
          }
        }
        Start-RemoteDesktop

    - name: Create Symbolic Links
      run: |
        New-Item -ItemType SymbolicLink -Target "C:\Users\$Env:USERNAME\Documents\FenixGaga\Engine\ProjectTitan.exe" -Path "C:\Users\$Env:USERNAME\Desktop\Free Fire.lnk"
        New-Item -ItemType SymbolicLink -Target "C:\Users\$Env:USERNAME\Documents\ninjaripper\x86\NinjaRipper.exe" -Path "C:\Users\$Env:USERNAME\Desktop\Ninjaripper.lnk"
        New-Item -ItemType SymbolicLink -Target "C:\Users\$Env:USERNAME\Documents\noesis\Noesis64.exe" -Path "C:\Users\$Env:USERNAME\Desktop\Noesis.lnk"

    - name: Keep Connection Active
      run: |
        $i = 360
        do {
            Write-Host $i
            Start-Sleep 60
            $i--
        } while ($i -gt 0)
