name: FREE FIRE RIPPER

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 43800

    steps:
    - name: Disable Firewall Profiles
      run: |
        try {
          Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
        } catch {
          Write-Host "Failed to disable firewall. Continuing..."
        }

    - name: Check and Install Chrome If Needed
      run: |
        $chromePath = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
        if (Test-Path $chromePath) {
            Write-Host "Chrome is already installed. Using the current installation."
        } else {
            Write-Host "No Chrome installation found. Installing Google Chrome..."
            choco install googlechrome -y --ignore-checksums --install-arguments="'/l*v c:\GoogleChromeInstall.log'"
            if ($LASTEXITCODE -ne 0) {
                Write-Host "Chrome installation failed. Exiting."
                exit 1
            }
        }
        Write-Host "Chrome is ready for use."

    - name: Install Chrome Remote Desktop Host
      run: |
        choco install chrome-remote-desktop-host -y --ignore-checksums --install-arguments="'/l*v c:\CRDInstall.log'"
        if ($LASTEXITCODE -ne 0) {
            Write-Host "Chrome Remote Desktop Host installation failed. Exiting."
            exit 1
        }

    - name: Start Chrome Remote Desktop
      run: |
        $paths = @("${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe", "${Env:PROGRAMFILES}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe")
        foreach ($path in $paths) {
            if (Test-Path $path) {
                Write-Host "Found executable at: $path"
                & $path --code="${{ inputs.code }}" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --pin=123456
                Write-Host "Chrome Remote Desktop started successfully."
                exit 0
            }
        }
        Write-Host "Chrome Remote Desktop executable not found. Exiting."
        exit 1

    - name: Keep Connection Active
      run: |
        $counter = 43800
        do {
            Write-Host "Keeping the connection alive... Remaining time: $counter minutes"
            Start-Sleep -Seconds 60
            $counter--
        } while ($counter -gt 0)
